namespace tomatocube {
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.Look.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.Look.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.WalkFrame1.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.WalkFrame2.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.WalkFrame3.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.WalkFrame1.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.WalkFrame2.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.WalkFrame3.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.TailUp.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.TailUp.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.MouthOpen.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.MouthOpen.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.Jump.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.Jump.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.Pale.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDino.Pale.Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEgg.Yellow = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEgg.Teal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEgg.Beige = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEgg.Rainbow = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesFlag = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesCloud1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesCloud2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesCloud3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesGhost.Red = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesGhost.Blue = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrow.Up = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrow.Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrow.Down = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrow.Left = image.ofBuffer(hex``);
}
