namespace tomatocube {
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoLookRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoLookLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoWalkFrame1Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoWalkFrame2Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoWalkFrame3Right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoWalkFrame1Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoWalkFrame2Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoWalkFrame3Left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoTailUpRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoTailUpLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoMouthOpenRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoMouthOpenLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoJumpRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoJumpLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoPaleRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesDinoPaleLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEggYellow = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEggTeal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEggBeige = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesEggRainbow = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesFlag = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesCloud1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesCloud2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesCloud3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesGhostRed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesGhostBlue = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrowUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrowRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrowDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const spritesArrowLeft = image.ofBuffer(hex``);
}
